# PlatformIO configuration for compiling WAMR on ESP32-S3 via ESP-IDF framework
[platformio]
src_dir = main

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

# Allocate partition layout
board_build.partitions = partitions.csv

# Compiler definitions and optimisation flags
build_flags =
    -D CORE_DEBUG_LEVEL=3
